image: ghcr.io/home-ast/{arch}-homeassistant
build_from:
  aarch64: ghcr.io/home-ast/aarch64-homeassistant-base:2024.11.0
  armhf: ghcr.io/home-ast/armhf-homeassistant-base:2024.11.0
  armv7: ghcr.io/home-ast/armv7-homeassistant-base:2024.11.0
  amd64: ghcr.io/home-ast/amd64-homeassistant-base:2024.11.0
  i386: ghcr.io/home-ast/i386-homeassistant-base:2024.11.0
codenotary:
  signer: notary@home-assistant.io
  base_image: notary@home-assistant.io
cosign:
  base_identity: https://github.com/home-ast/docker/.*
  identity: https://github.com/home-ast/core/.*
labels:
  io.hass.type: core
  org.opencontainers.image.title: Home Assistant
  org.opencontainers.image.description: Open-source home automation platform running on Python 3
  org.opencontainers.image.source: https://github.com/home-assistant/core
  org.opencontainers.image.authors: The Home Assistant Authors
  org.opencontainers.image.url: https://www.home-assistant.io/
  org.opencontainers.image.documentation: https://www.home-assistant.io/docs/
  org.opencontainers.image.licenses: Apache License 2.0
