image: ghcr.io/home-ast/{machine}-homeassistant
build_from:
  aarch64: "ghcr.io/home-ast/aarch64-homeassistant:"
  armv7: "ghcr.io/home-ast/armv7-homeassistant:"
  armhf: "ghcr.io/home-ast/armhf-homeassistant:"
  amd64: "ghcr.io/home-ast/amd64-homeassistant:"
  i386: "ghcr.io/home-ast/i386-homeassistant:"
codenotary:
  signer: notary@home-assistant.io
  base_image: notary@home-assistant.io
cosign:
  base_identity: https://github.com/home-ast/core/.*
  identity: https://github.com/home-ast/core/.*
labels:
  io.hass.type: core
  org.opencontainers.image.source: https://github.com/home-ast/core
